apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry
  namespace: davy
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: registry-secret-store
    kind: ClusterSecretStore
  target:
    name: vault-registry-secret
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: registry/selectel-1
        property: .dockerconfigjson